# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HyZIautwqDy8dtmug7ISflpS0qbmIERV
"""

# Import necessary libraries
import pandas as pd
import matplotlib.pyplot as plt

# Load the CSV file (adjust the file path as needed)
file_path = '/content/ai.csv'  # Update path for your environment
data = pd.read_csv(file_path)

# Display the first few rows to understand the structure
print(data.head())

# Assuming we want to plot a line graph
plt.figure(figsize=(10, 6))
plt.plot(data['House Number'], data['price'], marker='o', linestyle='-', color='blue')

# Add title and labels
plt.title('Example Graph for Real Estate annalysis', fontsize=14)
plt.xlabel('House number (X-axis Label)', fontsize=12)
plt.ylabel('Price (Y-axis Label)', fontsize=12)

# Show the plot
plt.grid(alpha=0.5)
plt.tight_layout()
plt.show()

